name: flutter_mediator_persistence
description: A super easy state management package with built in persistence capability, base on the Flutter Mediator Lite.
version: 1.0.2
homepage: https://github.com/rob333/flutter_mediator_persistence

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
